"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 18:33:11.916047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('gate_id', sa.String(length=16), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_kind'), 'alerts', ['kind'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=48), nullable=False),
    sa.Column('row_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('gate_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('last_seen', app.db.UTCDateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('stalled_alerted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gates',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('to', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_status'), 'message_log', ['status'], unique=False)
    op.create_table('overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('original_paise', sa.Integer(), nullable=False),
    sa.Column('new_paise', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overrides_created_at'), 'overrides', ['created_at'], unique=False)
    op.create_table('plate_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('camera_ids', sa.JSON(), nullable=False),
    sa.Column('raw_plate', sa.String(length=24), nullable=True),
    sa.Column('chosen_plate', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_corrections_event_id'), 'plate_corrections', ['event_id'], unique=False)
    op.create_table('relay_inbox',
    sa.Column('msg_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('applied_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('pin_hash', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle_classes',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bank_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('slip_ref', sa.String(length=64), nullable=False),
    sa.Column('slip_photo_path', sa.String(length=256), nullable=True),
    sa.Column('deposited_by', sa.Integer(), nullable=False),
    sa.Column('deposited_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('bank_status', sa.String(length=12), nullable=False),
    sa.Column('bank_credited_paise', sa.Integer(), nullable=True),
    sa.Column('reconciled_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deposited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_deposits_business_date'), 'bank_deposits', ['business_date'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('gate_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('rtsp_url', sa.String(length=512), nullable=False),
    sa.Column('roi', sa.JSON(), nullable=False),
    sa.Column('capture_line', sa.JSON(), nullable=False),
    sa.Column('in_vector', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pass_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('period_unit', sa.String(length=8), nullable=False),
    sa.Column('period_value', sa.Integer(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_class'], ['vehicle_classes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', app.db.UTCDateTime(), nullable=False),
    sa.Column('first_slab_minutes', sa.Integer(), nullable=False),
    sa.Column('first_slab_paise', sa.Integer(), nullable=False),
    sa.Column('per_hour_paise', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('block_minutes', sa.Integer(), nullable=False),
    sa.Column('block_cap_paise', sa.Integer(), nullable=True),
    sa.Column('daily_cap_paise', sa.Integer(), nullable=True),
    sa.Column('overnight_paise', sa.Integer(), nullable=False),
    sa.Column('overnight_cutoff_hour', sa.Integer(), nullable=False),
    sa.Column('free_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_class'], ['vehicle_classes.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_class', 'version')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('plate_canon', sa.String(length=16), nullable=False),
    sa.Column('display_plate', sa.String(length=24), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('first_seen', app.db.UTCDateTime(), nullable=False),
    sa.Column('last_seen', app.db.UTCDateTime(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('balance_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_class'], ['vehicle_classes.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index(op.f('ix_vehicles_balance_paise'), 'vehicles', ['balance_paise'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_canon'), 'vehicles', ['plate_canon'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gate_id', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('pass_type_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('remind_5d_sent', sa.Boolean(), nullable=False),
    sa.Column('remind_1d_sent', sa.Boolean(), nullable=False),
    sa.Column('auto_renew_reminders', sa.Boolean(), nullable=False),
    sa.Column('sold_by', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pass_type_id'], ['pass_types.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passes_ends_at'), 'passes', ['ends_at'], unique=False)
    op.create_index(op.f('ix_passes_vehicle_id'), 'passes', ['vehicle_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('closed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('opening_cash_paise', sa.Integer(), nullable=False),
    sa.Column('upi_total_paise', sa.Integer(), nullable=False),
    sa.Column('cash_total_paise', sa.Integer(), nullable=False),
    sa.Column('handed_over_paise', sa.Integer(), nullable=False),
    sa.Column('variance_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    op.create_table('worker_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('shift_label', sa.String(length=32), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wz_zone_time', 'worker_zones', ['zone_id', 'starts_at', 'ends_at'], unique=False)
    op.create_table('cash_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('expected_paise', sa.Integer(), nullable=False),
    sa.Column('declared_paise', sa.Integer(), nullable=False),
    sa.Column('declared_denoms', sa.JSON(), nullable=False),
    sa.Column('counted_paise', sa.Integer(), nullable=True),
    sa.Column('counted_denoms', sa.JSON(), nullable=True),
    sa.Column('variance_paise', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('photo_path', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('declared_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('confirmed_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_index(op.f('ix_cash_handovers_declared_at'), 'cash_handovers', ['declared_at'], unique=False)
    op.create_index(op.f('ix_cash_handovers_from_user'), 'cash_handovers', ['from_user'], unique=False)
    op.create_table('parking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('entry_event_id', sa.String(length=64), nullable=True),
    sa.Column('exit_event_id', sa.String(length=64), nullable=True),
    sa.Column('entry_gate', sa.String(length=16), nullable=True),
    sa.Column('exit_gate', sa.String(length=16), nullable=True),
    sa.Column('entry_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('exit_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('est_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('parked_location', sa.String(length=64), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('charge_paise', sa.Integer(), nullable=True),
    sa.Column('entry_match', sa.String(length=16), nullable=True),
    sa.Column('exit_match', sa.String(length=16), nullable=True),
    sa.Column('unpaid_flagged', sa.Boolean(), nullable=False),
    sa.Column('closed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_sessions_entry_at'), 'parking_sessions', ['entry_at'], unique=False)
    op.create_index(op.f('ix_parking_sessions_status'), 'parking_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_parking_sessions_vehicle_id'), 'parking_sessions', ['vehicle_id'], unique=False)
    op.create_table('anpr_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('gate_id', sa.String(length=16), nullable=False),
    sa.Column('camera_ids', sa.JSON(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('wrong_way', sa.Boolean(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=16), nullable=False),
    sa.Column('ts', app.db.UTCDateTime(), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('raw_plate', sa.String(length=24), nullable=True),
    sa.Column('plate_norm', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_reason', sa.String(length=64), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=16), nullable=True),
    sa.Column('match_distance', sa.Integer(), nullable=True),
    sa.Column('matched_plate', sa.String(length=16), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_events_plate_norm'), 'anpr_events', ['plate_norm'], unique=False)
    op.create_index(op.f('ix_anpr_events_status'), 'anpr_events', ['status'], unique=False)
    op.create_index(op.f('ix_anpr_events_ts'), 'anpr_events', ['ts'], unique=False)
    op.create_index('ix_evt_gate_plate_ts', 'anpr_events', ['gate_id', 'plate_norm', 'ts'], unique=False)
    op.create_table('payment_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('claimed_paise', sa.Integer(), nullable=True),
    sa.Column('claimed_mode', sa.String(length=8), nullable=False),
    sa.Column('claimed_when', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('raised_by_role', sa.String(length=16), nullable=False),
    sa.Column('raised_by_user', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_index(op.f('ix_payment_disputes_created_at'), 'payment_disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_disputes_vehicle_id'), 'payment_disputes', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_payment_disputes_worker_id'), 'payment_disputes', ['worker_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('base_paise', sa.Integer(), nullable=False),
    sa.Column('dues_paise', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('txn_ref', sa.String(length=40), nullable=False),
    sa.Column('gateway_ref', sa.String(length=64), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=64), nullable=True),
    sa.Column('utr', sa.String(length=64), nullable=True),
    sa.Column('upi_uri', sa.Text(), nullable=True),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('client_created_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('override_id', sa.Integer(), nullable=True),
    sa.Column('limit_breach', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('confirmed_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid'),
    sa.UniqueConstraint('txn_ref')
    )
    op.create_index(op.f('ix_payments_collected_by'), 'payments', ['collected_by'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_gateway_order_id'), 'payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payments_session_id'), 'payments', ['session_id'], unique=False)
    op.create_index(op.f('ix_payments_shift_id'), 'payments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_vehicle_id'), 'payments', ['vehicle_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_vehicle_id'), 'ledger_entries', ['vehicle_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('delivery_status', sa.String(length=12), nullable=False),
    sa.Column('synced_to_relay', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('delivered_at', app.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_receipts_created_at'), 'receipts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_created_at'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_ledger_entries_vehicle_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_payments_vehicle_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_shift_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_collected_by'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_disputes_worker_id'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_vehicle_id'), table_name='payment_disputes')
    op.drop_index(op.f('ix_payment_disputes_created_at'), table_name='payment_disputes')
    op.drop_table('payment_disputes')
    op.drop_index('ix_evt_gate_plate_ts', table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_ts'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_status'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_plate_norm'), table_name='anpr_events')
    op.drop_table('anpr_events')
    op.drop_index(op.f('ix_parking_sessions_vehicle_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_status'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_entry_at'), table_name='parking_sessions')
    op.drop_table('parking_sessions')
    op.drop_index(op.f('ix_cash_handovers_from_user'), table_name='cash_handovers')
    op.drop_index(op.f('ix_cash_handovers_declared_at'), table_name='cash_handovers')
    op.drop_table('cash_handovers')
    op.drop_index('ix_wz_zone_time', table_name='worker_zones')
    op.drop_table('worker_zones')
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_passes_vehicle_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_ends_at'), table_name='passes')
    op.drop_table('passes')
    op.drop_table('zones')
    op.drop_index(op.f('ix_vehicles_plate_canon'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_balance_paise'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('tariffs')
    op.drop_table('pass_types')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_bank_deposits_business_date'), table_name='bank_deposits')
    op.drop_table('bank_deposits')
    op.drop_table('vehicle_classes')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('relay_inbox')
    op.drop_index(op.f('ix_plate_corrections_event_id'), table_name='plate_corrections')
    op.drop_table('plate_corrections')
    op.drop_index(op.f('ix_overrides_created_at'), table_name='overrides')
    op.drop_table('overrides')
    op.drop_index(op.f('ix_message_log_status'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_table('gates')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_kind'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
